### PR TITLE
restore non-pump-insulin upload to Tidepool

### PR DESCRIPTION
**Pull request by marionbarker**
This is a fix for [Loop Issue 2024](https://github.com/LoopKit/Loop/issues/2024).

Both commits are required. Testing added in next comment.

### CODE REVIEW

**Comment by marionbarker** [comment]
I did this by trial and error, so not really sure if this is the best fix.

Trial was to only call a single function under `private func dataForBolus` and determine which of the three functions included in the `if` block would successfully upload non-pump insulin to Tidepool.

Of the 3 originally found in this function, `dataForBolusManuallyEntered` was the only function that did not successfully provide that data to Tidepool.

So I removed that as an option. With this version, I tested these methods for entering a bolus on the loop phone and confirmed that in all cases, Tidepool shows the value. For each test, I refreshed Tidepool after adding or removing an entry from Loop.

```
non-pump: 1.15 U: Tidepool: yes
AH add:   0.35 U: Tidepool: yes
Toolbar:  0.85 U: Tidepool: yes
AB:       0.25 U: Tidepool: yes
```

Discovered that non-pump insulin was not removed from Tidepool with just the first commit, so added the second commit and now both non-pump insulin and Apple Health insulin are added to and removed from Tidepool as expected.

```
01:52 pm: non-pump: 1.05 U: Tidepool: yes
  02:05 pm delete from Loop
  02:07 pm gone from Tidepool
02:08 pm: AH add:   0.85 U: Tidepool: yes
  02:09 pm delete from AH
  02:10 pm gone from Tidepool
```

**Comment by ps2** [comment]
I think this needs an additional annotation... Will check with the backend team.

**Comment by marionbarker** [comment]
@ps2 Please respond. This has the advantage of recording non-pump insulin, whereas what is currently in Loop does not.

**Comment by marionbarker** [comment]
Add this information from the notes I kept while developing this fix. Note that I have used this for months and my Tidepool Bolus record is correct for the days when I use non-pump insulin. Without this fix, the non-pump insulin is not registered.

Notes from `20240129_Issue_2024_Tidepool_non-pump-insulin.txt`:
* Found a commit that might be related - this change occurred before this Issue was first reported:
   * commit 66beb59 in LoopKit/TidepoolService
   * https://github.com/LoopKit/TidepoolService/commit/66beb59d4e844b79dae9cb2213404a783938e2f0#diff-76c3c27ace0d2c9e3e58fa02a4167690058971805baad2504bf22d83f84e4784L103-L109

* Find in workspace dataForBolusManuallyEntered and dataForBolusManual and dataForBolusAutomatic
   * private func dataForBolusManuallyEntered
   * private func dataForBolusManual
   * private func dataForBolusAutomatic

I did a bunch of tests adding extra print statements and breakpoints to determine that the Tidepool work-around found in this PR provides the expected bolus values to Tidepool. It both adds non-pump insulin and removes non-pump insulin when edited in the Loop app.

I am not sure that Tidepool has the concept of insulin delivered by injection as opposed to insulin delivered manually through the pump. This maintains the automated vs manual bolus for Loop correctly.

**Comment by ps2** [comment]
Thanks Marion. I think this is a valid workaround until the .insulin type is better supported on the Tidepool frontend. I created a new PR as I wanted to have a comment in the code about eventual reverting and wanted to annotate the dose in some form. https://github.com/LoopKit/TidepoolService/pull/22

**Pull request closed without merging**
